---
output: github_document
---
```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  dev = "png",
  dpi = 500,
  fig.align = "center"
)
```


# hypMuVar: Bayesian Hypothesis  <br/> Testing of Mean-Variance Relations


## Overview
## Installation
```{r, eval=F}
# install.packages("devtools")
devtools::install_github("donaldRwilliams/hypMuVar")
```


```{r}
library(hypMuVar)
```


## Random slopes for the location and scale:
```{r,eval=F}
fit <- melsm(fixed_location = rt ~  congruency,
             random_location = ~  congruency | ID,
             fixed_scale = sigma ~  congruency,
             random_scale = ~ congruency | ID,  
             mixture = "SSVS", k = 3,
             adapt = 5000, 
             iter = 10000, 
             data = stroop)
```

```{r,echo=F}
load("C:/Users/willidon/Box Sync/r_packages/rmd_files/fit.Rdata")
```

```{r, eval=T, set-options, echo=-1}
options(width = 250)
summary(fit)
```

### Marginal Bayes Factors
k2 (positive component) vs. the compliment
```{r}
bf <- marginal_bf(fit, H1 = "k2")

bf
```

k2 (positive component) vs. k1(null component)
```{r}
# note testing against the compliment is preferable
bf <- marginal_bf(fit, H1 = "k2", H2 = "k1")

bf
```

### Posterior Model Probabilities
```{r}
prob <- model_prob(fit)

prob
````
